package org.example.model;

public enum UserState {

    IDLE,
    WAITING_FOR_TITLE,

    WAITING_FOR_DESCRIPTION,

    WAITING_FOR_DEADLINE,

    WAITING_FOR_PRIORITY,

    WAITING_FOR_CATEGORY,

    WAITING_FOR_NEW_CATEGORY_NAME,

    WAITING_FOR_NEW_CATEGORY_COLOR,

    WAITING_FOR_DELETE_TASK_ID,

    WAITING_FOR_STATUS_TASK_ID,

    WAITING_FOR_NEW_STATUS,

    WAITING_FOR_STANDALONE_CATEGORY_NAME,

    WAITING_FOR_STANDALONE_CATEGORY_COLOR,

    WAITING_FOR_DELETE_CATEGORY_ID,

    WAITING_FOR_CATEGORY_CHOICE,

    WAITING_FOR_ASSIGN_TASK_ID,

    WAITING_FOR_ASSIGN_CATEGORY_CHOICE,

    WAITING_FOR_ASSIGN_CATEGORY_ID,

    WAITING_FOR_ASSIGN_NEW_CATEGORY_NAME,

    WAITING_FOR_ASSIGN_NEW_CATEGORY_COLOR

}